name: mcMMO
main: com.gmail.nossr50.mcMMO
version: ${project.version}-b${BUILD_NUMBER}
softdepend: [Spout]
authors:
  - TheYeti
  - nossr50
  - NuclearW
  - gmcferrin
description: mcMMO takes core Minecraft game mechanics and expands them to add an extensive RPG experience, the goal of the project has always been a quality RPG experience. Everything in mcMMO is carefully thought out and is constantly improving. mcMMO adds eleven skills to train in and level in, while also offering a high level of customization for server admins. There are countless features, including custom sounds, graphical elements, and more added when running mcMMO in conjunction with Spout. I carefully read feedback and evaluate the mechanics of mcMMO in every update to provide an ever-evolving experience.
commands:
    mchud:
        description: Change your HUD
    xplock:
        description: Lock your xp bar
    xprate:
        description: Modify the xp rate or start an event
    mcc:
        description: Lists mcMMO commands
    mcmmo:
        description: Shows a brief mod description
    mctop:
        description: Shows leader boards for mcMMO
    addxp:
        description: Add XP to a user
        permission: mcmmo.tools.mmoedit
    addlevels:
        description: Add levels to a user
        permission: mcmmo.tools.mmoedit
    deity:
        description: Deities command
    loselevels:
        description: Lose levels to self
    mcability:
        description: Toggle whether or not abilities get readied on right click
        permission: mcmmo.commands.ability
    mcrefresh:
        description: Refresh all cooldowns for mcMMO
        permission: mcmmo.tools.mcrefresh
    mcgod:
        description: Make yourself invulnerable
        permission: mcmmo.tools.mcgod        
    mcstats:
        description: Shows your mcMMO stats and xp
    mcremove:
        description: Remove a user from the database
    mmoedit:
        description: Edit the skill values for a user
        permission: mcmmo.tools.mmoedit
    ptp:
        description: Teleport to a party member
        permission: mcmmo.commands.ptp
    party:
        description: Create/join a party
        permission: mcmmo.commands.party
    inspect:
        description: View mcMMO stats of another player
    invite:
        description: Invite a player into your party
        permission: mcmmo.chat.partychat
    accept:
        description: Accept a party invite
        permission: mcmmo.chat.partychat
    mmoupdate:
        description: Convert from Flat File to MySQL
        permission: mcmmo.admin
    p:
        description: Toggle Party chat or send party chat messages
        permission: mcmmo.chat.partychat
    excavation:
        description: Detailed skill info
    herbalism:
        description: Detailed skill info
    mining:
        description: Detailed skill info
    woodcutting:
        description: Detailed skill info
    axes:
        description: Detailed skill info
    archery:
        description: Detailed skill info
    swords:
        description: Detailed skill info
    taming:
        description: Detailed skill info
    unarmed:
        description: Detailed skill info
    acrobatics:
        description: Detailed skill info
    repair:
        description: Detailed skill info
    fishing:
        description: Detailed skill info
    a:
        description: Toggle Admin chat or send admin chat messages
        permission: mcmmo.chat.adminchat
permissions:
    mcmmo.*:
        description: Implies all mcmmo permissions.
        children:
            mcmmo.defaults: true
            #Instead of containing mcmmo.defaultsop on its own, it should specify each of mcmmo.defaultsop
            mcmmo.admin: true
            mcmmo.tools.*: true
            mcmmo.chat.adminchat: true 
    mcmmo.defaults:
        default: true
        description: mcmmo permisions that default to true
        children:
            mcmmo.ability.*: true 
            mcmmo.item.*: true   
            mcmmo.motd: true 
            mcmmo.commands.*: true 
            mcmmo.chat.partychat: true 
            mcmmo.skills.*: true
    mcmmo.defaultsop:
        default: op
        description: mcmmo permissions that default to op
        children:
            mcmmo.chat.adminchat: true
            mcmmo.admin: true
            mcmmo.tools.*: true
    mcmmo.admin:
        description: Allows access to mmoupdate and other sensitive commands        
    mcmmo.tools.*:
        description: Implies all mcmmo.tools permissions.
        children:
            mcmmo.tools.mcrefresh: true 
            mcmmo.tools.mmoedit: true 
            mcmmo.tools.mcgod: true 
    mcmmo.tools.mcrefresh:
        description: Allows access to mcrefresh command
    mcmmo.tools.mmoedit:
        description: Allows access to mmoedit command
    mcmmo.tools.mcgod:
        description: Allows access to mcgod command        
    mcmmo.ability.*:
        description: Implies all mcmmo.ability permissions.
        children:
            mcmmo.ability.herbalism: true 
            mcmmo.ability.excavation: true 
            mcmmo.ability.unarmed: true 
            mcmmo.ability.mining: true 
            mcmmo.ability.axes: true 
            mcmmo.ability.swords: true 
            mcmmo.ability.woodcutting: true 
    mcmmo.ability.herbalism:
        description: Allows access to Green Terra ability
    mcmmo.ability.excavation:
        description: Allows access to Giga Drill Breaker ability
    mcmmo.ability.unarmed:
        description: Allows access to Berserker ability
    mcmmo.ability.mining:
        description: Allows access to Super Breaker ability
    mcmmo.ability.axes:
        description: Allows access to Skull Splitter ability
    mcmmo.ability.swords:
        description: Allows access to Serrated Strikes ability
    mcmmo.ability.woodcutting:
        description: Allows access to Tree Feller ability        
    mcmmo.item.*:
        description: Implies all mcmmo.item permissions.
        children:
            mcmmo.item.chimaerawing: true 
    mcmmo.item.chimaerawing:
        description: Allows use of Chimaera Wing item            
    mcmmo.motd:
        description: Allows access to the motd        
    mcmmo.commands.*:
        description: Implies all mcmmo.commands permissions.
        children:
            mcmmo.commands.ability: true  
            mcmmo.commands.ptp: true 
            mcmmo.commands.inspect: true 
            mcmmo.commands.party: true 
    mcmmo.commands.ability:
        description: Allows access to the mcability command
    mcmmo.commands.ptp:
        description: Allows access to the ptp command
    mcmmo.commands.inspect:
        description: Allows access to the inspect command
    mcmmo.commands.party:
        description: Allows acces to the party command        
    mcmmo.chat.*:
        description: Implies all mcmmo.chat permissions. (Warning, contains adminchat)
        children:
            mcmmo.chat.adminchat: true 
            mcmmo.chat.partychat: true 
    mcmmo.chat.adminchat:
        description: Allows participation in admin chat
    mcmmo.chat.partychat:
        description: Allows participation in party chat
    mcmmo.skills.*:
        description: Implies all mcmmo.skills permissions.
        children:
            mcmmo.skills.fishing: true
            mcmmo.skills.taming: true 
            mcmmo.skills.mining: true 
            mcmmo.skills.woodcutting: true 
            mcmmo.skills.repair: true 
            mcmmo.skills.unarmed: true 
            mcmmo.skills.archery: true 
            mcmmo.skills.herbalism: true 
            mcmmo.skills.excavation: true 
            mcmmo.skills.swords: true 
            mcmmo.skills.axes: true 
            mcmmo.skills.acrobatics: true
            mcmmo.skills.blastmining: true
    mcmmo.skills.taming:
        description: Allows access to the Taming skill
    mcmmo.skills.mining:
        description: Allows access to the Mining skill
    mcmmo.skills.woodcutting:
        description: Allows access to the Woodcutting skill
    mcmmo.skills.repair:
        description: Allows access to the Repair skill
    mcmmo.skills.repair.arcanebypass:
        description: Allows user to bypass Arcane Repair so he will never lose enchantments
    mcmmo.skills.unarmed:
        description: Allows access to the Unarmed skill
    mcmmo.skills.archery:
        description: Allows access to the Archery skill
    mcmmo.skills.herbalism:
        description: Allows access to the Herbalism skill
    mcmmo.skills.excavation:
        description: Allows access to the Excavation skill
    mcmmo.skills.swords:
        description: Allows access to the Swords skill
    mcmmo.skills.axes:
        description: Allows access to the Axes skill
    mcmmo.skills.acrobatics:
        description: Allows access to the Acrobatics skill
    mcmmo.skills.blastmining:
        description: Allows access to the Blast Mining subskill for Mining